services:

    condominio_gerenc:
          build: .
          restart: always
          ports:
              - 8000:8000
          depends_on:
              - condominio_gerenc_db
    condominio_gerenc_db:
          image: postgres
          ports:
              - 5432:5432
          volumes:
              - postgres_data:/var/lib/postgresql/data
          environment:
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=mlovatto
              - POSTGRES_DB=gerenciador_condominio

volumes:
    postgres_data: